# Generated by Django 5.2.6 on 2025-09-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars_DB',
            fields=[
                ('car_name', models.CharField(max_length=30)),
                ('regno', models.IntegerField(primary_key=True, serialize=False)),
                ('carowner_email', models.EmailField(max_length=254)),
                ('carmanufacture_date', models.DateField()),
                ('car_mileage', models.FloatField()),
            ],
        ),
    ]
